export const countries = [
  { code: "AED", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "AUD", name: "Australia", flag: "🇦🇺" },
  { code: "BHD", name: "Bahrain", flag: "🇧🇭" },
  { code: "BND", name: "Brunei", flag: "🇧🇳" },
  { code: "CAD", name: "Canada", flag: "🇨🇦" },
  { code: "CHF", name: "Switzerland", flag: "🇨🇭" },
  { code: "CNY", name: "China", flag: "🇨🇳" },
  { code: "DKK", name: "Denmark", flag: "🇩🇰" },
  { code: "GBP", name: "United Kingdom", flag: "🇬🇧" },
  { code: "HKD", name: "Hong Kong", flag: "🇭🇰" },
  { code: "IDR", name: "Indonesia", flag: "🇮🇩" },
  { code: "JPY", name: "Japan", flag: "🇯🇵" },
  { code: "KRW", name: "South Korea", flag: "🇰🇷" },
  { code: "KWD", name: "Kuwait", flag: "🇰🇼" },
  { code: "MYR", name: "Malaysia", flag: "🇲🇾" },
  { code: "NOK", name: "Norway", flag: "🇳🇴" },
  { code: "NZD", name: "New Zealand", flag: "🇳🇿" },
  { code: "SAR", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SEK", name: "Sweden", flag: "🇸🇪" },
  { code: "SGD", name: "Singapore", flag: "🇸🇬" },
  { code: "THB", name: "Thailand", flag: "🇹🇭" },
  { code: "USD", name: "United States", flag: "🇺🇸" },
];
