/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/board` | `/board`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/currency` | `/currency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/api/axios`; params?: Router.UnknownInputParams; } | { pathname: `/api/fetchUserInfo`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signNationality`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUsername`; params?: Router.UnknownInputParams; } | { pathname: `/post/newpost`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/board` | `/board`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/currency` | `/currency`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/api/axios`; params?: Router.UnknownOutputParams; } | { pathname: `/api/fetchUserInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signIn`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signNationality`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signUsername`; params?: Router.UnknownOutputParams; } | { pathname: `/post/newpost`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/board${`?${string}` | `#${string}` | ''}` | `/board${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/currency${`?${string}` | `#${string}` | ''}` | `/currency${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/api/axios${`?${string}` | `#${string}` | ''}` | `/api/fetchUserInfo${`?${string}` | `#${string}` | ''}` | `/auth/signIn${`?${string}` | `#${string}` | ''}` | `/auth/signNationality${`?${string}` | `#${string}` | ''}` | `/auth/signUsername${`?${string}` | `#${string}` | ''}` | `/post/newpost${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/board` | `/board`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/currency` | `/currency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/api/axios`; params?: Router.UnknownInputParams; } | { pathname: `/api/fetchUserInfo`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signNationality`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUsername`; params?: Router.UnknownInputParams; } | { pathname: `/post/newpost`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
